-   id: pg_format
    name: pg_format
    entry: pg_format -i -L
    language: node
    'types': [sql]
    args: []
    require_serial: false
    additional_dependencies: ["pg-formatter@1.3.0"]
    minimum_pre_commit_version: '0'
    description: 'A PostgreSQL SQL syntax beautifier.'